"""empty message

Revision ID: f65f8a80dc25
Revises: e5fee90c912c
Create Date: 2022-08-25 15:16:28.784488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f65f8a80dc25'
down_revision = 'e5fee90c912c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_calendar',
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('calendar_id', 'user_id')
    )
    op.drop_constraint('calendars_user_id_fkey', 'calendars', type_='foreignkey')
    op.create_foreign_key(None, 'calendars', 'users', ['user_id'], ['id'])
    op.add_column('invites', sa.Column('accepted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invites', 'accepted')
    op.drop_constraint(None, 'calendars', type_='foreignkey')
    op.create_foreign_key('calendars_user_id_fkey', 'calendars', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_table('user_calendar')
    # ### end Alembic commands ###
