"""empty message

Revision ID: 9fc697828cb3
Revises: f8acb2027341
Create Date: 2022-08-02 16:01:37.889002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc697828cb3'
down_revision = 'f8acb2027341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('createdAt', sa.DateTime(), nullable=True))
    op.add_column('messages', sa.Column('updatedAt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'updatedAt')
    op.drop_column('messages', 'createdAt')
    # ### end Alembic commands ###
