"""empty message

Revision ID: 02f3f64b538c
Revises: acaf3f4f8a64
Create Date: 2022-08-04 09:24:02.123429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '02f3f64b538c'
down_revision = 'acaf3f4f8a64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'end_time')
    op.drop_column('events', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
