"""empty message

Revision ID: 08acb82fa3e9
Revises: dbc8ab2764f6
Create Date: 2022-08-26 18:21:38.770949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08acb82fa3e9'
down_revision = 'dbc8ab2764f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('calendar_title', sa.String(length=60), nullable=False))
    op.add_column('invites', sa.Column('sender_username', sa.String(length=60), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invites', 'sender_username')
    op.drop_column('invites', 'calendar_title')
    # ### end Alembic commands ###
