"""empty message

Revision ID: 558a0e9974ba
Revises: 02f3f64b538c
Create Date: 2022-08-04 09:58:11.973979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '558a0e9974ba'
down_revision = '02f3f64b538c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'end_date')
    op.drop_column('events', 'start_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
