"""empty message

Revision ID: 3033e9248e8e
Revises: 52267b6ef7dd
Create Date: 2022-08-03 10:51:10.653449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3033e9248e8e'
down_revision = '52267b6ef7dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'description')
    # ### end Alembic commands ###
